### ISSUE TITLE
Code compatibility with CadQuery Editor

### ISSUE THREAD

**Issue by roipoussiere** [roipoussiere/cadquery-server#1]
This is now a meta issue that lists all steps required for CadQuery Editor compatibility:

- [x] #8
- [x] #34
- [x] #35
- [x] #36

**Comment by fpq473** [comment]
Highlighting some ways in which you may wish to match the CQ-editor experience:

- `debug()` is red with alpha 20% (you guesstimated 50% above): [source](https://github.com/CadQuery/CQ-editor/blob/774c3c62b872a4ffb73de3f6a4052ddcad68a7c8/cq_editor/widgets/debugger.py#L206-L208)

- There are several globals injected when running the code: [source](https://github.com/CadQuery/CQ-editor/blob/774c3c62b872a4ffb73de3f6a4052ddcad68a7c8/cq_editor/widgets/debugger.py#L210-L213)

- If `show_object()` isn't called then globals are searched for workplanes: [source](https://github.com/CadQuery/CQ-editor/blob/774c3c62b872a4ffb73de3f6a4052ddcad68a7c8/cq_editor/widgets/debugger.py#L292-L293)

**Comment by roipoussiere** [comment]
fixed in 09b0360
