### ISSUE TITLE
consider supporting cqgi

### ISSUE THREAD

**Issue by roipoussiere** [roipoussiere/cadquery-server#44]
See [CadQuery Gateway Interface documentation](https://cadquery.readthedocs.io/en/latest/cqgi.html) and [cqgi python script](https://github.com/CadQuery/cadquery/blob/master/cadquery/cqgi.py).

Basically it could be a python script on the user project used to build the models and the ui inputs.

**Comment by dcowden** [comment]
cqgi unit tests are here:
https://github.com/CadQuery/cadquery/blob/master/tests/test_cqgi.py

I think an update to cqgi is needed to allow scripts to provide type hints, and infer typing from those.

One example that was mentioned as a requirement is a value with min, max, and step values.  Step values are not currently supported by CQGI, but would be implemented by creating a subclass of InputParameter, and overriding set_value to raise an error if the value is not in the step

**Comment by dcowden** [comment]
BTW, PRs on cqgi would be very welcome to bring it into the modern age. For most cases, a script containing 

```
import typing
diameter: Int = 3
```
should work when we want to declare only the variable type

**Comment by roipoussiere** [comment]
fixed in 09b0360 and 91bf79d
