### ISSUE TITLE
minor fixes

### ISSUE THREAD

**Issue by roipoussiere** [roipoussiere/cadquery-server#64]
website index page:
- `get svg` -> `get stl`
- improve link appearance
- make images corners round
- click outside title doesn't work

readme:
- section *using-the-web-server*: add `:5000` to the url

other might be added with edit or comment, go ahead. :)

**Comment by jdegenstein** [comment]
![image](https://user-images.githubusercontent.com/16868537/190832899-bb0ec42b-ecef-4d04-969b-ab66baaa02b7.png)
Sorry if this is a repeat, but would it be possible to add XYZ labels to this object? The reason I think it is important is that selectors often operate using e.g. ">X" and if it was labeled it would be a little easier for new users of cq-server.

**Comment by roipoussiere** [comment]
I think it's a good idea, but this project doesn't include the code of the user interface.
Would you like to create an issue on https://github.com/bernhard-42/three-cad-viewer?

**Comment by roipoussiere** [comment]
fixed in 8652c9474f22c988fa8dd421a843dbdd7d678075, 7e901433cb3a780b138e1e39dcccc5b5d80bab08, f3a2c01dbef18eb43b8cda4e4c0b92dc4c17cee7 and 94d5f51414ef61c37a6b72da2e3ca83ca7ec645e

Please re-open if necessary.
